- name: Gitops con Openshift y Ansible
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    namespace: emsya-dev
  module_defaults:
    group/k8s:
      namespace: "{{ namespace }}"
      api_key: "sha256~NPrH2KnMvu-bjYMtzCD7TI91v7USMV8dwZm43ox26Vo"
      host: https://api.sandbox.x8i5.p1.openshiftapps.com:6443
  tasks:
    - name: Crear objetos desde la especificacion
      k8s:
        state: present
        src: "{{ playbook_dir + '/hello.yml' }}"
        
    - name: Cambiar de ClusterIP a NodePort
      k8s_service:
        state: present
        name: nodejs-ex
        type: NodePort
        ports:
          - port: 8080
            protocol: TCP
            
    - name: Obtener informacion sobre los pods desplegados
      k8s_info:
        kind: Pod
        label_selectors:
          - app = nodejs-ex
          
    - name: Exponer el servicio https con ClusterIP
      k8s_service:
        state: present
        name: nodejs-ex
        ports:
          - port: 443
            protocol: TCP
        selector:
          app: nodejs-ex
