---
- name: Demostrar los modulos k8s
  hosts: localhost
  gather_facts: no
  connection: local
  module_defaults:
    group/k8s:
      namespace: "{{ namespace }}"
      api_key: "{{ myapikey }}"
      host: https://api.sandbox.x8i5.p1.openshiftapps.com:6443
  tasks:
    - name: Eliminar objetos desde el manifiesto
      k8s:
        state: absent
        src: "{{ playbook_dir + '/hello.yml' }}"
